name: CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install deps
        run: npm ci
      - name: Check format
        run: npm run fmt-check
      - name: Test
        run: npm run test
